kind = "web"
previewPath = "/"
title = "CereBloom"
version = "1.0.0"
id = "XegfDyZt7HqfW2Bb8Ghoy"

[[services]]
localPort = 5000
name = "CereBloom"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace/cerebloom && streamlit run app.py --server.port 5000 --server.address 0.0.0.0"

[services.production]

[services.production.run]
args = ["sh", "-c", "cd /home/runner/workspace/cerebloom && streamlit run app.py --server.port 5000 --server.address 0.0.0.0"]

[services.production.run.env]
PORT = "5000"
